"""empty message

Revision ID: 383ae7984fb5
Revises: 2e0f102ede58
Create Date: 2013-12-04 12:08:29.986116

"""

# revision identifiers, used by Alembic.
revision = '383ae7984fb5'
down_revision = '2e0f102ede58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    ### end Alembic commands ###
