"""empty message

Revision ID: ec6eabee2e1
Revises: 383ae7984fb5
Create Date: 2013-12-04 12:13:29.948987

"""

# revision identifiers, used by Alembic.
revision = 'ec6eabee2e1'
down_revision = '383ae7984fb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category_name', sa.String(length=10), nullable=True))
    op.drop_index('name', 'category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'category', [u'name'], unique=True)
    op.drop_column('articles', 'category_name')
    ### end Alembic commands ###
